### ISSUE TITLE
Adding Account Number and Vendor Information to Bill view

### ISSUE THREAD

**Issue by lweeksnrg** [NRGCSDevelopers/Billtrak-Public#1]
Can the Bill Information tab please include the Acct Number of the invoice and Utility/Vendor?

**Comment by bgarrison25** [comment]
Testing comments and webhook integration

**Comment by bgarrison25** [comment]
Pushed to Dev server and ready for testing

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/BillTrak#5
