### ISSUE TITLE
Tonnage sub tab in Sites

### ISSUE THREAD

**Issue by lweeksnrg** [NRGCSDevelopers/Billtrak-Public#14]
Please create a tab next to Accounts in the Site tab to display the history of tonnage uploaded into the portal

**Comment by lweeksnrg** [comment]
Can we also please display tonnage by month and allow users to select the month and get a pop up window with all days data was uploaded for displayed?

**Comment by lweeksnrg** [comment]
Can we please add commas to the tonnage import numbers when displayed in the site view? also, can we limit the values after the decimal to 2 please? i.e. 24050.577680 -> 24,050.58

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/BillTrak#18
