### ISSUE TITLE
Analytics Sub tab

### ISSUE THREAD

**Issue by lweeksnrg** [NRGCSDevelopers/Billtrak-Public#18]
Once the tonnage upload tab and tonnage sub tab in Sites is uploaded, can we please add "Analytics" as the next sub tab under Sites? 

This tab will feature should display; 

Electric Cost/Tonnage (Electricity Bill Amount/aggregate tonnage per corresponding start and end date)
Electric Usage/Tonnage (Electricity Usage/aggregate tonnage per corresponding start and end date)
water cost/ton (water bill amount/aggregate tonnage per corresponding start and end date)
water usage/ton (water usage/aggregate tonnage per corresponding start and end date)

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/BillTrak#22
