### ISSUE TITLE
Sites Tab update

### ISSUE THREAD

**Issue by lweeksnrg** [NRGCSDevelopers/Billtrak-Public#19]
Please change the header ribbon values to display Electric Usage, Gas Usage, and Water Usage (in that order) after Facility Type since we're adding the rates to the analytics tab.

**Comment by lweeksnrg** [comment]
looks great! can we possibly add commas in the facility size values? i.e. 12000 be 12,000?

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/BillTrak#23
