### ISSUE TITLE
Search Drop Down Menu

### ISSUE THREAD

**Issue by lweeksnrg** [NRGCSDevelopers/Billtrak-Public#2]
Hi there,

Can we please create a drop down menu for the Search Tab that would allow clients/Arctic Glacier to search their profile by; 

Account Number
Meter Number
Site Name
Site Number 
Vendor

This would cut down on the number of filters we'd need on each page thereafter.

**Comment by bgarrison25** [comment]
Can we get a screenshot of the current functionality in Cass's system?

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/BillTrak#6
