### ISSUE TITLE
Admin Report Function

### ISSUE THREAD

**Issue by lweeksnrg** [NRGCSDevelopers/Billtrak-Public#3]
Could you please add a report segment into the admin view (internal only) so that we can run a report based on account number to determine if we've received a PDF invoice for all accounts within the last 25 days of the due date of the previous invoice on file?

We need Account number, utility, and a Y/N field when generated and an inventory list for all account numbers on file. It doesn't matter if there are accounts that are invoiced quarterly or bi monthly that will appear on the report more frequently, we need notification to check. 

Please let me know if you have any questions!

**Comment by bgarrison25** [comment]
This issue was moved to NRGCSDevelopers/BillTrak#7
